---
title: "Class_08"
author: "Joshua Chevez"
date: "February 6, 2019"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Class 08


```{r}
tmp <- c(rnorm(30,-3), rnorm(30,3))
x <- cbind(x=tmp, y=rev(tmp))
plot(x)
```



```{r}
km <- kmeans(x, 2, nstart=20)
km
```

Size of clusters
```{r}
km$size
```

```{r}
km$cluster
```

```{r}
plot(x, col=km$cluster)
points(km$centers, col="blue", pch=15, cex=3)
```

##Heirarchial Clustering

```{r}
# First we need to calculate point (dis)similarity
# as the Euclidean distance between observations
dist_matrix <- dist(x)
# The hclust() function returns a hierarchical
# clustering model
hc <- hclust(d = dist_matrix)
# the print method is not so useful here
hc 
```

```{r}
plot(hc)
abline(h=6, col="red")
grp2 <- cutree(hc, h=6)
```

```{r}
plot(x, col=grp2)
```

```{r}
plot(hc)
abline(h=2.5, col="blue")
grp6 <- cutree(hc, h=2.5)
table(grp6)
```

We can also use k= groups as an argument to cutree

```{r}
cutree(hc, k=2)
```

```{r}
d <- dist_matrix
```

```{r}
# Using different hierarchical clustering methods
hc.complete <- hclust(d, method="complete")
plot(hc.complete)
hc.average <- hclust(d, method="average")
plot(hc.average)
hc.single <- hclust(d, method="single")
plot(hc.single)
```

```{r}
# Step 1. Generate some example data for clustering
x <- rbind(
 matrix(rnorm(100, mean=0, sd = 0.3), ncol = 2), # c1
 matrix(rnorm(100, mean = 1, sd = 0.3), ncol = 2), # c2
 matrix(c(rnorm(50, mean = 1, sd = 0.3), # c3
 rnorm(50, mean = 0, sd = 0.3)), ncol = 2))
colnames(x) <- c("x", "y")
# Step 2. Plot the data without clustering
plot(x)
# Step 3. Generate colors for known clusters
# (just so we can compare to hclust results)
col <- as.factor( rep(c("c1","c2","c3"), each=50) )
plot(x, col=col)


```


```{r}
d <- dist(x)
n <- hclust(d)
plot(n)
grps <- cutree(n, k=3)
plot(x, col=grps)
```

#PCA in R

```{r}
mydata <- read.csv("https://tinyurl.com/expression-CSV",
 row.names=1)
head(mydata)
```


```{r}
## lets do PCA
pca <- prcomp(t(mydata), scale=TRUE)
summary(pca)
```

Make our first PCA plot

```{r}
dim(pca$x)
plot(pca$x[,1], pca$x[,2])
```


```{r}
## lets do PCA
pca <- prcomp(t(mydata), scale=TRUE)
## A basic PC1 vs PC2 2-D plot
plot(pca$x[,1], pca$x[,2])
## Precent variance is often more informative to look at
pca.var <- pca$sdev^2
pca.var.per <- round(pca.var/sum(pca.var)*100, 1)

pca.var.per
```

```{r}
pca.var <- pca$sdev^2
pca.var.per <- round(pca.var/sum(pca.var)*100, 1)

barplot(pca.var.per, main="Scree Plot",
 xlab="Principal Component", ylab="Percent Variation")
```

```{r}
## A vector of colors for wt and ko samples
colvec <- as.factor( substr( colnames(mydata), 1, 2) )
plot(pca$x[,1], pca$x[,2], col=colvec, pch=16,
 xlab=paste0("PC1 (", pca.var.per[1], "%)"),
 ylab=paste0("PC2 (", pca.var.per[2], "%)")) 

```

```{r}
x = read.csv("UK_foods.csv")
ncol(x)
nrow(x)
View(x)
rownames(x) <- x[,1]

```
Simper way of changing the first column to be the row names
```{r}
x = read.csv("UK_foods.csv", row.names = 1)
View(x)
```

```{r}
barplot(as.matrix(x), beside=T, col=rainbow(nrow(x)))
```

```{r}
pairs(x, col=rainbow(10), pch=16)
```

#PCA
```{r}
# Use the prcomp() PCA function 
pca <- prcomp( t(x) )
summary(pca)
```
Make PCA plot
```{r}
plot(pca$x[,1], pca$x[,2])
text(pca$x[,1], pca$x[,2], labels = colnames(x), col=c("orange", "red", "blue", "darkgreen"))
```


```{r}
## Lets focus on PC1 as it accounts for > 90% of variance 
par(mar=c(10, 3, 0.35, 0))
barplot( pca$rotation[,1], las=2 )
```














