---
title: "Class 6 R functions"
author: "Joshua Chevez"
date: "January 25, 2019"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



Here we try to use **rad.tabl()** and friends to input some example data into R

lets insert a code chunk,

```{r}
read.table("https://bioboot.github.io/bggn213_W19/class-material/test1.txt", header = TRUE, sep = ",")
```

```{r}
file1 <- "https://bioboot.github.io/bggn213_W19/class-material/test1.txt"
read.csv(file1)
```

```{r}
file2 <- "https://bioboot.github.io/bggn213_W19/class-material/test2.txt"
read.table(file2, sep = "$")
```

```{r}
file3 <- "https://bioboot.github.io/bggn213_W19/class-material/test3.txt"
read.table(file3)
```


##R Functions

My first function
```{r}
add <- function(x, y=1) {
# Sum the input x and y
 x + y
}
```

Lets use the **add()**
```{r}
add(1)
```

```{r}
add(c(1, 2, 3, 4))
```

```{r}
#add(1, 2, 2)
```

```{r}
#add(x=1, y="b")
```


```{r}
rescale <- function(x) {
 rng <-range(x)
 (x - rng[1]) / (rng[2] - rng[1])
}
```

```{r}
rescale(1:10)
```

```{r}
rescale( c(1,2,NA,3,10) )
```


```{r}
x <- c(1,2,NA,3,10)
rng <-range(x)
rng
# (x - rng[1]) / (rng[2] - rng[1])
```

```{r}
rescale2 <- function(x) {
 rng <-range(x, na.rm=TRUE)
 (x - rng[1]) / (rng[2] - rng[1])
}
```

```{r}
rescale(c(1, 2, NA, 3, 10))
```

```{r}
#rescale(c(1, 2, NA, 3, 10, "bggn213"))
```

```{r}
rescale3 <- function(x, na.rm=TRUE, plot=FALSE) {
 if(na.rm) {
 rng <-range(x, na.rm=na.rm)
 } else {
 rng <-range(x)
 }
 print("Hello")
 answer <- (x - rng[1]) / (rng[2] - rng[1])
 print("is it me you are looking for?")
 if(plot) {
 plot(answer, typ="b", lwd=4)
   
 }
 print("please don't sing again")
 print("I can see it in ...")
 print(answer)
}
```

```{r}
rescale3(1:10)
```

```{r}
rescale3(1:10, plot=FALSE)
```


##Using the bio3d package

```{r}
library(bio3d)
```


```{r}
pdb <- read.pdb("1hbs")
```

What is **pdb**

```{r}
pdb
```


```{r}
library(bio3d)
s1 <- read.pdb("4AKE") # kinase with drug
s2 <- read.pdb("1AKE") # kinase no drug
s3 <- read.pdb("1E4Y") # kinase with drug
s1.chainA <- trim.pdb(s1, chain="A", elety="CA")
s2.chainA <- trim.pdb(s2, chain="A", elety="CA")
s3.chainA <- trim.pdb(s3, chain="A", elety="CA")
s1.b <- s1.chainA$atom$b
s2.b <- s2.chainA$atom$b
s3.b <- s3.chainA$atom$b
plotb3(s1.b, sse=s1.chainA, typ="l", ylab="Bfactor")
plotb3(s2.b, sse=s2.chainA, typ="l", ylab="Bfactor")
plotb3(s3.b, sse=s3.chainA, typ="l", ylab="Bfactor")

```

#My Function (Homework)

```{r}
PD <- function(x) {
  s <- read.pdb(x)
  s.chainA <- trim.pdb(s, chain="A", elety="CA")
s.b <- s.chainA$atom$b
plotb3(s.b, sse = s.chainA, type = "l", ylab = "Bfactor")
}
```

```{r}
PD("4AKE")
PD("1AKE")
PD("1E4Y")
```















