---
title: "Class 7 Functions and Packages"
author: "Joshua Chevez"
date: "January 30, 2019"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

##Functions revisited

Load(i.e.**source**) our rescale() function from last day.

```{r}
source("http://tinyurl.com/rescale-R")
```

Test this function

```{r}
rescale(1:5)
```

```{r eval=FALSE}
rescale(c(1:5, "string"))
```

We want to make this function more robust to these types of errors

```{r eval=FALSE}
rescale2(c(1:5, "string"))
```

```{r}
is.numeric(1:5)
```

```{r}
is.numeric("string")
```

```{r}
is.numeric(c(1:5, "string"))
```

```{r}
!is.numeric(c(1:5, "string"))
```

```{r}
!is.numeric(c(1:5))
```

```{r}
x <- c( 1, 2, NA, 3, NA)
y <- c(NA, 3, NA, 3, 4)
```


```{r}
is.na(x)
is.na(y)
is.na(x) & is.na(y)
#How many NA elements in both vectors
sum(is.na(x) & is.na(y))
#what position is the NAx2
which(is.na(x) & is.na(y))
```

Now take our working snippet and make a first function

```{r}
both_na <- function(x, y) {
sum(is.na(x) & is.na(y)) 
}
```


```{r}
both_na(x, y)
```

```{r}
x1 <- c(NA, NA, NA)
y1 <- c( 1, NA, NA)
y2 <- c( 1, NA, NA, NA)
y3 <- c(1, NA, NA, NA, NA)
both_na(x1, y3)
#shorter vectors repeat
```

```{r eval= FALSE}
both_na2(x1, y2)
```

```{r}
both_na3(x, y)
```








